apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-vaultkubenertes-job
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-vaultkubenertes-job
  chart:
    git: https://github.com/renjithpta/bafhlf.git
    ref: local
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: carrier
      component_name: carrier-net
      component_type: peer
      namespace: carrier-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    checks:
      vault_auth_status_exits: True
      vault_policy_not_exits: False

    vault:
      role: vault-role
      address: http://13.235.23.226:8200
      authpath: localcarrier-net-auth
      policy: vault-crypto-peer-carrier-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://172.17.0.4:8443
