---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies-config-{{ .Values.metadata.component_type }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: policies-config
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  policies-config-orderer.json.tmpl: |-
    {"policy":"path \"{{ .Values.vault.secret_path }}/data/crypto/ordererOrganizations/{{ .Values.metadata.component_name }}/*\" {\n capabilities = [\"list\", \"read\"]\n}     \npath \"{{ .Values.vault.secret_path }}/*\" {\n capabilities = [\"list\"]\n}     \npath \"{{ .Values.vault.secret_path }}/data/crypto/peerOrganizations/*\" {\n capabilities = [\"deny\"]\n}     \npath \"{{ .Values.vault.secret_path }}/data/credentials/{{ .Values.metadata.component_name }}/*\" {\n capabilities = [\"list\", \"read\"]\n}"}
  policies-config-peer.json.tmpl: |-
    {"policy":"path \"{{ .Values.vault.secret_path }}/*\" {\n capabilities = [\"list\"]\n}     \npath \"{{ .Values.vault.secret_path }}/data/crypto/ordererOrganizations/*\" {\n capabilities = [\"deny\"]\n}     \npath \"{{ .Values.vault.secret_path }}/data/credentials/{{ .Values.metadata.component_name }}/*\" {\n capabilities = [\"list\", \"read\"]\n}     \npath \"{{ .Values.vault.secret_path }}/data/crypto/peerOrganizations\" {\n capabilities = [\"deny\"]\n}     \npath \"{{ .Values.vault.secret_path }}/data/crypto/peerOrganizations/*\" {\n capabilities = [\"deny\"]\n}     \npath \"{{ .Values.vault.secret_path }}/data/crypto/peerOrganizations/{{ .Values.metadata.component_name }}/*\" {\n capabilities = [\"list\", \"read\"]\n}"}
