metadata:
  #Provide organization's name
  #Eg. namespace: org1
  name:
  #Provide organization's component_name
  #Eg. namespace: org1-net
  component_name:
  #Provide organization's type (orderer or peer)
  #Eg. namespace: orderer
  component_type:
  #Provide the namespace for organization's peer
  #Eg. namespace: org1-example-com
  namespace: default
  images:
    #Provide the valid image name and version for fabric tools
    #Eg. fabric-tools: hyperledger/fabrictools:1.4.0
    fabrictools:
    #Provide the valid image name and version to read certificates from vault server
    #Eg.alpineutils: hyperledgerlabs/alpine-utils:1.0
    alpineutils:
  #Provide the custom labels
  #NOTE: Provide labels other than name, release name , release service, chart version , chart name , app.
  #Eg. labels:
  #      role: anchorpeer
  labels:

  checks:
    #Provides the existence of the auth vault
    #Eg. vault_auth_status_exits: false
    vault_auth_status_exits:
    #Provides the non-existence of the policy in the vault
    #Eg. vault_policy_not_exits: true
    vault_policy_not_exits:

vault:
  #Provide the vaultrole for an organization
  #Eg. vaultrole: org1-vault-role
  role:
  #Provide the vault server address
  #Eg. vaultaddress: http://Vault-884963190.eu-west-1.elb.amazonaws.com
  address:
  #Provide the kubernetes auth backed configured in vault for an organization
  #Eg. authpath: fra-demo-hlkube-cluster-org1
  authpath:
  #Provide the vault policy name
  #Eg. policy: vault-crypto-orderer-net-org1-ro
  policy:
  #Provide the value for vault secretprefix
  #Eg. adminsecretprefix: secret/...
  secret_path:
  #Provide the serviceaccountname for vault
  #Eg. serviceaccountname: vault-auth
  serviceaccountname:
  #Provide the imagesecretname for vault
  #Eg. imagesecretname: regcred
  imagesecretname:
  #Kuberenetes secret for vault ca.cert
  #Enable or disable TLS for vault communication if value present or not
  #Eg. tls: vaultca
  tls:

k8s:
  #Provide the kubernetes host url
  #Eg. kubernetes_url: https://10.3.8.5:6443
  kubernetes_url: 
