---
# Task to transfer did and seed vaules from one secret engine to another

# Transfer DID and Seed Values between Vaults
- name: "Transfer DID and Seed Values between Vaults"
  shell: |
    new_org={{ organization }}
    new_org_role="stewards";
    new_org_alias={{ stewardItem.name }}

    trustee_seed=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$new_org/data/trustees/$new_org-trustee/identity/private | jq -j ".data.data.seed")
    trustee_did=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$new_org/data/trustees/$new_org-trustee/identity/public | jq -j ".data.data.did")
    trustee_verkey=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$new_org/data/trustees/$new_org-trustee/node/public/verif_keys | jq -j ".data.data.\"verification-key\"")
      
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"data": {"seed": "'"$trustee_seed"'"}}' {{ vault.url }}/v1/$new_org/data/$new_org_role/$new_org_alias/trustee/private    
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"data": {"did": "'"$trustee_did"'"}}' {{ vault.url }}/v1/$new_org/data/$new_org_role/$new_org_alias/trustee/public
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"data": {"verkey": "'"$trustee_verkey"'"}}' {{ vault.url }}/v1/$new_org/data/$new_org_role/$new_org_alias/trustee/node
    
  loop: "{{ services.stewards }}"
  when: services.stewards is defined
  loop_control:
    loop_var: stewardItem

    
